"""Reversible, uncertainty-driven navigation over Beast Watch evidence."""
from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass
from pathlib import Path

from .core import (extract_frame, format_time, frame_name, hamming_hash,
                   perceptual_hash)


class SeekError(RuntimeError):
    pass


@dataclass(frozen=True)
class SeekLevel:
    name: str
    before: float
    after: float
    fps: float
    purpose: str


SEEK_LEVELS = {
    # L0 is the original adaptive overview generated by beast watch.
    1: SeekLevel("context", 6.0, 6.0, 1.0,
                 "establish what led into and followed the selected state"),
    2: SeekLevel("action", 3.0, 3.0, 4.0,
                 "resolve a click, value change, connection, or short interaction"),
    3: SeekLevel("forensic", 1.5, 1.5, 10.0,
                 "inspect a rapid or ambiguous transition at high temporal density"),
}


def resolve_center(timeline: dict, *, at: float | None = None,
                   frame_id: str | None = None) -> float:
    if at is not None:
        return at
    if frame_id:
        row = next((row for row in timeline.get("frames", [])
                    if row.get("id") == frame_id), None)
        if row:
            return float(row["source_seconds"])
        raise SeekError(f"frame not found: {frame_id}")
    raise SeekError("provide --at or --frame-id")


def seek_times(center: float, source_start: float, source_end: float, *,
               before: float, after: float, fps: float,
               direction: str = "both") -> list[float]:
    if direction not in ("back", "forward", "both"):
        raise SeekError("direction must be back, forward, or both")
    if fps <= 0 or fps > 30 or before < 0 or after < 0:
        raise SeekError("fps must be 0..30 and seek extents cannot be negative")
    start = center if direction == "forward" else center - before
    end = center if direction == "back" else center + after
    start, end = max(source_start, start), min(source_end, end)
    if end < start:
        return []
    step = 1.0 / fps
    count = int((end - start) / step) + 1
    values = [round(start + index * step, 3) for index in range(count)]
    if values and values[-1] < end - step * 0.25:
        values.append(round(end, 3))
    return values


def _bundle_fingerprint(frames: list[dict]) -> str:
    payload = "\n".join(
        f"{row.get('source_seconds')}:{row.get('perceptual_hash')}"
        for row in sorted(frames, key=lambda item: item["source_seconds"]))
    return hashlib.sha256(payload.encode()).hexdigest()


def reinspect(bundle: Path, ffmpeg: str, *, center: float, level: int = 2,
              direction: str = "both", before: float | None = None,
              after: float | None = None, fps: float | None = None,
              reason: str = "uncertain visual action") -> dict:
    """Extract missing neighboring evidence and atomically revise timeline.json."""
    timeline_path = bundle / "timeline.json"
    if not timeline_path.exists():
        raise SeekError(f"timeline not found: {timeline_path}")
    timeline = json.loads(timeline_path.read_text(encoding="utf-8"))
    if level not in SEEK_LEVELS:
        raise SeekError("seek level must be 1, 2, or 3")
    preset = SEEK_LEVELS[level]
    before = preset.before if before is None else before
    after = preset.after if after is None else after
    fps = preset.fps if fps is None else fps
    source_range = timeline["source"]["range"]
    source_start = float(source_range["start_seconds"])
    source_end = float(source_range["end_seconds"])
    if not source_start <= center <= source_end:
        raise SeekError(
            f"seek center {format_time(center)} is outside bundle range "
            f"{source_range['start']}–{source_range['end']}; rerun beast watch on a wider range")
    video = bundle / timeline["source"]["local_video"]
    if not video.is_file():
        raise SeekError(f"bundle video missing: {video}")

    requested = seek_times(center, source_start, source_end, before=before,
                           after=after, fps=fps, direction=direction)
    frames = timeline.setdefault("frames", [])
    existing = {round(float(row["source_seconds"]), 3): row for row in frames}
    added = []
    frames_dir = bundle / "frames"
    frames_dir.mkdir(exist_ok=True)
    height = int(timeline.get("sampling", {}).get("height", 900))
    for source_seconds in requested:
        if source_seconds in existing:
            reasons = existing[source_seconds].setdefault("reasons", [])
            tag = f"seek_l{level}"
            if tag not in reasons:
                reasons.append(tag)
            continue
        destination = frames_dir / frame_name(source_seconds)
        clip_seconds = source_seconds - source_start
        if not extract_frame(ffmpeg, video, clip_seconds, destination, height):
            continue
        row = {
            "id": "", "file": destination.relative_to(bundle).as_posix(),
            "source_seconds": source_seconds, "source_time": format_time(source_seconds),
            "clip_seconds": round(clip_seconds, 3),
            "reasons": ["targeted_dense", f"seek_l{level}"],
            "perceptual_hash": perceptual_hash(destination),
            "change_from_previous": None, "near_duplicate": False,
        }
        frames.append(row)
        added.append(row)

    frames.sort(key=lambda row: float(row["source_seconds"]))
    previous_hash = None
    for index, row in enumerate(frames, 1):
        row["id"] = f"frame-{index:04d}"
        distance = hamming_hash(previous_hash, row.get("perceptual_hash"))
        row["change_from_previous"] = distance
        row["near_duplicate"] = bool(
            distance is not None and distance <= 3
            and not any(reason.startswith("seek_l") for reason in row.get("reasons", [])))
        previous_hash = row.get("perceptual_hash")

    request = {
        "id": f"seek-{len(timeline.get('evidence_requests', [])) + 1:04d}",
        "created_unix": time.time(), "center_seconds": center,
        "center_time": format_time(center), "level": level, "level_name": preset.name,
        "direction": direction, "before_seconds": before, "after_seconds": after,
        "fps": fps, "reason": reason, "requested_frames": len(requested),
        "new_frames": len(added),
    }
    timeline.setdefault("evidence_requests", []).append(request)
    coverage = timeline.setdefault("coverage", {})
    coverage["extracted_frames"] = len(frames)
    coverage["dense_samples"] = sum(
        "targeted_dense" in row.get("reasons", []) for row in frames)
    coverage["near_duplicates"] = sum(bool(row.get("near_duplicate")) for row in frames)
    timeline["bundle_fingerprint"] = _bundle_fingerprint(frames)
    timeline["visual_index_stale"] = (bundle / "visual-index.json").exists()
    temporary = timeline_path.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(timeline, indent=2), encoding="utf-8")
    temporary.replace(timeline_path)
    return request


def escalation_for(confidence: float, missing_evidence: bool = False,
                   rapid_action: bool = False) -> int | None:
    """Recommend the smallest reinspection level justified by uncertainty."""
    if not 0 <= confidence <= 1:
        raise ValueError("confidence must be between 0 and 1")
    if rapid_action or confidence < 0.35:
        return 3
    if missing_evidence or confidence < 0.65:
        return 2
    if confidence < 0.85:
        return 1
    return None
